Responsive-desktop-version
IfzaRasool/Portfolio-desktop-version pull request #1
Opened 2021-12-09 19:27 UTC by IfzaRasool

**Project: Responsive Web Design for desktop**

> <hr>

- For responsive use media queries in CSS
- Use semantic markup
- Use Grid and flex in CSS
- Add Validation in contact Form

2021-12-09 22:01 UTC, Gambit142 requested changes
Hi @IfzaRasool 👋,
 
Good job so far!

## To Highlight

- Good `README.md` file 👍 
- All Linters checks passed 👍 
- Good Pull Request title 👍 

However, there are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 10:46 UTC, IfzaRasool commented on Icons/index.html
> +                  <input  class="name-field" type="text" id="name" name="user_name" placeholder="Name" minlength="4" maxlength="30" required>
![image](https://user-images.githubusercontent.com/93009273/145561710-de462ff7-e7e2-40de-b8bc-f5e2281c61ba.png)
In requirement is no need to create a last name text field.

2021-12-10 10:48 UTC, IfzaRasool commented on Icons/index.html
> +                  <input  class="name-field" type="text" id="name" name="user_name" placeholder="Name" minlength="4" maxlength="30" required>
![image](https://user-images.githubusercontent.com/93009273/145561944-46227106-7143-43de-91a8-78d78df75168.png)
 In requirement, there is no need to create a last name field.

2021-12-10 11:44 UTC, elyor-doniyorov requested changes
Hi @IfzaRasool, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 11:44 UTC, elyor-doniyorov commented on index.html
> +    <div class="app-wrap">
- [ ] Let's make changes to the design a little bit. I can see your design is not covering the full width of your viewport but your portfolio still has some white patches as the previous reviewer said. Please look at the first comment of the previous reviewer. Kindly fix it before going ahead.

2021-12-10 11:44 UTC, elyor-doniyorov commented on index.html
> +                <div class="contact-form-divisor"></div>
- [ ] Good job implementing the changes asked by the previous reviewer on the footer section. However, it would be better if you make your line with class "contact-form-divisor" full width. Let's compare Figma design with your's:

Your footer 👇 
![student](https://user-images.githubusercontent.com/67087664/145569135-5c088652-2d70-4728-b0d2-0b5d27b360e6.jpg)
Figma 👇 
![figma](https://user-images.githubusercontent.com/67087664/145569192-728213d2-9ce7-4b88-aec8-cba5edad3474.jpg)

2021-12-10 12:50 UTC, IfzaRasool commented on index.html
> +    <div class="app-wrap">
![image](https://user-images.githubusercontent.com/93009273/145576565-3afa0d2c-1593-4eda-98fc-8fdc3f77f3d9.png)
i don't understand what you mean by white patches. i make width:100%

2021-12-10 20:17 UTC, MrBrN197 approved these changes
## Hi, @IfzaRasool 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 21:20 UTC, merged