Portfolio mobile menu
IfzaRasool/Portfolio-desktop-version pull request #6
Opened 2021-12-21 11:33 UTC by IfzaRasool

## Mobile-Menu

> Add Hamburger menu using Javascript

> Add links in header option

> Display the nav link in the overlay and add javascript to get and set style.

2021-12-21 11:53 UTC, ShoiraTa requested changes
Hi team,

This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 11:53 UTC, ShoiraTa commented on app.js
> +const closeIcon = document.querySelector('.closeIcon');
- [ ] When the page loads first time, the `closeIcon` button is visible next to `humburger` button, please check the logic and make it invisible when the modal is close

![image](https://user-images.githubusercontent.com/77038610/146924062-0246adaa-d4a8-47e8-81e1-fa6986a14a84.png)

2021-12-21 11:53 UTC, ShoiraTa commented on index.html
> +                <i class="closeIcon material-icons">close</i>
- [ ] I suggest you to align the `close` btn on the same level as the logo, this way the page will look much more professional 👍🏻 :

Yours  | Figma
------------- | -------------
![image](https://user-images.githubusercontent.com/77038610/146924544-170075cc-bb54-473d-a906-04c835bc22af.png)  | ![image](https://user-images.githubusercontent.com/77038610/146924515-308339fe-acfa-4efb-86fe-cba9f4583316.png)

You can easily do it by setting: 
```
.app-header {
    align-items: center;
}
.hamburger {
    top: -0.5rem;
}
```

- [ ][OPTIONAL]  I suggest you to match the design with Figma to fully comply with the requirements, I noticed that when the modal is open, the `close` btn is not properly positioned:

Figma  | Yours
------------- | -------------
![image](https://user-images.githubusercontent.com/77038610/146925312-eed4ddc4-812b-4cc5-a1f9-56f5b79b4c0c.png)  | ![image](https://user-images.githubusercontent.com/77038610/146925271-00fc3411-3dd3-4746-8a64-faa5d74d1458.png)

2021-12-21 16:49 UTC, alonsofl requested changes
Hi @IfzaRasool and @steveWDamesJr,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media2.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 16:49 UTC, alonsofl commented on index.html
> +                  <li><a class="nav-link" href="#"><img src="Icons/mail.png" alt="message-icon"></a></li>
- [ ] Good job addressing the issue with the (X) :muscle: but there is a new issue introduced because the arrows are not showing in the mobile menu. Please, kindly address this issue  in order to match the template :wink:

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/81522435/146966778-85fd6629-3441-489b-940c-4e7ac30eae75.png) | ![image](https://user-images.githubusercontent.com/81522435/146966814-99a23e7a-aea1-4d48-bc6f-a03de3bbf836.png) |

2021-12-21 16:49 UTC, alonsofl commented on styles.css
> +}
- [ ] [OPTIONAL] I think it could be a good idea to update the height for the mobile menu because when scrolling I can see the content behind and it could be a bad user experience. I will mark this as OPTIONAL because this wasn't addressed before but I strongly suggest fixing this issue with the mobile menu :pushpin: :smiley:
![image](https://user-images.githubusercontent.com/81522435/146967308-48341cda-d8d6-4430-9af4-4ffbe53d015c.png)
- [ ] [OPTIONAL] Also, when I scroll down the (X) icon stays on top of the page and it should move with the mobile menu. I strongly suggest fixing this issue for a better user experience :raised_hands:
![image](https://user-images.githubusercontent.com/81522435/146967548-db5fba56-f554-4321-9a46-30781d1aa080.png)

2021-12-22 11:36 UTC, VanessaAoki approved these changes
## STATUS: APPROVED 🟢 
Hi @IfzaRasool, 

Great job implementing all the changes required by the previous Code Reviewers, your project is complete! There is nothing else to say other than... it's time to merge it! 
Congratulations! 🎉 

<img alt="approved" src="https://64.media.tumblr.com/87e0b6469c957bf896cdec1cab646acf/tumblr_inline_pk1bdakCCp1rpcr9a_500.gif">

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Your README file looks very professional and the PR has a descriptive title/summary of the implemented changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 


Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 11:56 UTC, merged