Portfolio Popup Window
IfzaRasool/Portfolio-desktop-version pull request #9
Opened 2021-12-23 17:41 UTC by IfzaRasool

**Popup window**

> 

- Add EventListener on buttons using Javascript

- Refactor markup using Javascript

- Add Functionality on popup close icon

2021-12-23 17:51 UTC, MrBrN197 reviewed
## Hi, @IfzaRasool  @steveWDamesJr  👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a javascript project, that does not have ESlint linters setup
please use the correct linter setup.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-24 07:42 UTC, ShoiraTa requested changes
Hi @IfzaRasool ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Keep on coding, good job so far! :clap:

There are some minor issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 07:42 UTC, ShoiraTa commented on index.html
> +<button class="modal-button" type="submit">See Source</button>
- [ ] Please add the icons on buttons as given in Figma, match colors and make sure that text is not wrapping 😉 : 

Yours  | Figma
------------- | -------------
![image](https://user-images.githubusercontent.com/77038610/147329953-7ed6388a-1db2-4c4b-96e9-73a2d7944154.png) | ![image](https://user-images.githubusercontent.com/77038610/147329917-1ec3bbe6-0009-4474-b0ba-a03afab850bb.png)

2021-12-24 07:42 UTC, ShoiraTa commented on index.html
> +        <img  class="modal-close" src="Icons/modal-close.png" alt="close">
- [ ] I kindly suggest you to delete the extra margin to properly align items on modal, to compare:

Before  | After
------------- | -------------
![image](https://user-images.githubusercontent.com/77038610/147329516-29181186-0c5e-447b-a3c4-af3664ec79ad.png)  | ![image](https://user-images.githubusercontent.com/77038610/147329458-be8c405e-89ef-407e-87a4-64d2b8e87624.png)

You can also see that before, `x` button is too close to the right border, to fix this you can set the  `justify-content: space-around;` 😉 
If you apply these changes, your design will be the same as given in Figma 👍🏻

2021-12-24 09:02 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi again @IfzaRasool ,  

Now everything looks great!
Your project is complete! Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 09:05 UTC, merged